# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build Quirkful
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [
          17
        ]

        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: gradle
      - name: Make Gradle Wrapper Executable # Here in case we want to test other platforms in the future
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: quirkful-build-artifacts-${{ steps.ref.outputs.branch }}

          # Filter built files to disregard -sources and -dev, and leave only the Minecraft-compatible JARS.
          path: build/libs/*[0-9].jar